apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
data:
  KAFKA_CONNECT_STRING: b3JnLmFwYWNoZS5rYWZrYS5jb21tb24uc2VjdXJpdHkuc2NyYW0uU2NyYW1Mb2dpbk1vZHVsZSByZXF1aXJlZCB1c2VybmFtZT0id29ybF9mbG93IiBwYXNzd29yZD0id29ybF9mbG93Ijs=
